package at.bettertrack.app.data.db

import android.database.Cursor
import androidx.sqlite.db.SupportSQLiteDatabase
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File
import java.lang.reflect.Proxy
import java.nio.file.Files
import java.sql.Connection
import java.sql.DriverManager

/**
 * The migration chain, executed for real.
 *
 * Every other guarantee in this app is worth nothing if the database will not
 * open: [BtDatabase] deliberately has no `fallbackToDestructiveMigration()`
 * (the outbound queue is durable user data, §7.3), so a migration that does not
 * reproduce the schema Room's compiler expects does not degrade — it throws from
 * `validateMigration` inside the open transaction, which Room then repeats, and
 * fails identically, on every single launch. That is a crash loop whose only
 * user-visible escape is clearing app data, i.e. destroying the very queue the
 * no-fallback policy exists to protect.
 *
 * ## How this test gets its two sides
 *
 * **Expected** comes from the KSP-generated `BtDatabase_Impl`, not from a copy of
 * it: the test reflects the real `createAllTables` onto a scratch database. That
 * is byte-for-byte the shape `validateMigration` compares against, and it moves
 * automatically the moment an `@Entity` changes — a hand-maintained expectation
 * would just be a second thing to forget to update.
 *
 * **Actual** comes from building a database at a historical version and running
 * [BtDatabase.MIGRATIONS] — the same array [BtDatabase.create] registers — over
 * it. Real SQLite (sqlite-jdbc), real migration objects, real SQL.
 *
 * The comparison replicates Room's own `TableInfo` rules rather than diffing DDL
 * text: type AFFINITY (not the spelling), `NOT NULL`, primary-key position, the
 * default value only where the entity itself declares one, and the `index_`-
 * prefixed indices with their uniqueness and column order. Anything Room would
 * reject, this rejects; anything Room tolerates (column order, extra tables it
 * does not know about), this tolerates.
 *
 * ## Why the historical schemas are spelled out here
 *
 * They are written as literal SQL, each labelled with the git rev it was read
 * from, instead of being generated by replaying our own migrations. Replaying
 * the migrations to build the starting point would only prove the chain is
 * self-consistent; pinning the historical shapes independently is what lets this
 * test notice that the chain has drifted away from what shipped.
 *
 * [SCHEMA_V7_OWNER_DEVICE] is not a reconstruction at all — it is the `.schema`
 * of the owner's actual phone database, pulled over adb on 2026-08-05 while it
 * sat at `user_version = 7`. Only the shape is here; none of his rows are.
 *
 * From v11 on there is a third, better source: `exportSchema` is finally ON and
 * `app/schemas/at.bettertrack.app.data.db.BtDatabase/<version>.json` is
 * committed, so the newest steps start from the schema Room itself wrote rather
 * than from anybody's transcription of it. `MigrationTestHelper` — the androidx
 * way to consume those files — needs an instrumented device; this suite stays
 * device-free on purpose (it is a CI gate), so it consumes the same JSONs
 * through the same JDBC harness instead.
 */
class BtDatabaseMigrationTest {

    // ── The two defects this suite exists to keep fixed ──────────────────────

    /**
     * The owner's real device: `user_version = 7`, six portfolios of live data,
     * about to meet migrations 7→8, 8→9 and 9→10 for the first time.
     */
    @Test
    fun ownersRealV7DeviceSchemaMigratesToTheRoomExpectation() {
        withMigratedDb(SCHEMA_V7_OWNER_DEVICE, fromVersion = 7) { conn ->
            assertSchemaMatchesRoomExpectation(conn, "owner device v7 (adb dump 2026-08-05)")
        }
    }

    /** …and it must arrive there with every row still in it. */
    @Test
    fun ownersRealV7DeviceKeepsItsRowsAcrossTheMigration() {
        val db = newDbFile()
        openJdbc(db).use { conn ->
            conn.applyAll(SCHEMA_V7_OWNER_DEVICE)
            conn.exec("PRAGMA user_version = 7")
            conn.applyAll(SAMPLE_ROWS_V7)
            val before = conn.rowCounts(COUNTED_TABLES)
            assertEquals("fixture should have seeded every counted table", 0, before.count { it.value == 0 })

            runMigrations(conn, from = 7)

            val after = conn.rowCounts(COUNTED_TABLES)
            assertEquals("migration 7→10 must not touch a single user row", before, after)
            // The two columns the chain adds to existing rows land at their
            // documented "this row predates the feature" values, not NULL.
            assertEquals("", conn.single("SELECT DISTINCT `tagIds` FROM `cash_movements`"))
            assertEquals(null, conn.single("SELECT `errorCode` FROM `sync_ops` LIMIT 1"))
        }
    }

    /**
     * Rev `3a8ca5f` shipped `sync_ops.firstAttemptAtMs` while `@Database` still
     * said `version = 4` and added no migration, so a fresh install from that
     * window is a version-4 database that ALREADY has the column. Unguarded,
     * `MIGRATION_4_5` greets it with `duplicate column name`.
     */
    @Test
    fun versionFourTwinThatAlreadyHasFirstAttemptAtMsStillMigrates() {
        withMigratedDb(SCHEMA_V4 + DELTA_FIRST_ATTEMPT_AT_MS, fromVersion = 4) { conn ->
            assertSchemaMatchesRoomExpectation(conn, "v4 twin from rev 3a8ca5f")
        }
    }

    /**
     * Rev `ac316e1` (the W4 vault branch) declared `version = 8` for a schema
     * that has the vault tables but NOT the cash-classification work, while the
     * merged mainline's version 8 means the opposite. Nothing later in the chain
     * used to add the cash columns to that twin, so it failed `validateMigration`
     * at the end of 8→9→10 with no migration left to blame.
     */
    @Test
    fun versionEightTwinFromTheVaultBranchStillMigrates() {
        withMigratedDb(SCHEMA_V7 + DELTA_VAULT_TABLES, fromVersion = 8) { conn ->
            assertSchemaMatchesRoomExpectation(conn, "v8 twin from rev ac316e1")
        }
    }

    // ── The whole chain, every entry point ───────────────────────────────────

    @Test
    fun everyHistoricalVersionMigratesToTheRoomExpectation() {
        HISTORICAL_SCHEMAS.forEach { (version, schema) ->
            withMigratedDb(schema, fromVersion = version) { conn ->
                assertSchemaMatchesRoomExpectation(conn, "database created at v$version")
            }
        }
    }

    /**
     * A migration that exists but is never registered is a migration that does
     * not run; a gap in the chain is a hard `IllegalStateException` at open.
     */
    @Test
    fun theRegisteredChainIsUnbrokenFromOneToTheDeclaredVersion() {
        // `@Database` has CLASS retention, so the schema version is read where it
        // actually matters at runtime: off the generated open delegate.
        val declared = roomOpenDelegate().let { delegate ->
            delegate.javaClass.getMethod("getVersion").apply { isAccessible = true }.invoke(delegate) as Int
        }
        val steps = BtDatabase.MIGRATIONS.map { it.startVersion to it.endVersion }.sortedBy { it.first }

        assertEquals("every migration must advance exactly one version", emptyList<Pair<Int, Int>>(), steps.filter { it.second != it.first + 1 })
        assertEquals("no duplicate start versions", steps.size, steps.map { it.first }.toSet().size)
        assertEquals("chain must start at 1", 1, steps.first().first)
        assertEquals("chain must end at the declared @Database version", declared, steps.last().second)
        assertEquals("chain must have no gaps", (1 until declared).toList(), steps.map { it.first })
    }

    /**
     * Cross-check on the git archaeology: the v7 schema reconstructed from the
     * entity definitions at rev `4b24c6c` must be the schema the owner's phone
     * actually holds. If these ever disagree, the reconstructions the rest of
     * this file relies on are fiction.
     */
    @Test
    fun reconstructedV7MatchesTheOwnersDevice() {
        val real = schemaFrom(SCHEMA_V7_OWNER_DEVICE)
        val reconstructed = schemaFrom(SCHEMA_V7)
        assertEquals("tables", real.keys.sorted(), reconstructed.keys.sorted())
        // Compared with Room's rules, not byte-for-byte: his `custom_assets` was
        // CREATEd at v4 while the reconstruction ALTERs into v4, so the table
        // carries `DEFAULT 0` on `smoothing` in one and not the other. Room reads
        // both as the same schema, and it is Room's opinion that decides whether
        // an app opens.
        assertEquals("reconstructed v7 differs from the device", emptyList<String>(), diffSchemas(real, reconstructed))
    }

    // ── The exported schema JSONs (app/schemas), now that they exist ─────────
    //
    // `exportSchema` was `false` for eleven versions — a long-flagged defect,
    // because the export is what makes a migration reviewable and what lets a
    // test start from the schema that ACTUALLY shipped rather than from a
    // reconstruction of it. It is on from v11 forward: 11.json was exported
    // before the v12 work, 12.json with it, and both are committed.

    /** Every committed export must be a schema this code still agrees with. */
    @Test
    fun theCommittedSchemaExportsMatchTheRoomExpectation() {
        val declared = declaredVersion()
        assertEquals("the newest export must be the declared version", declared, exportedVersions().max())
        assertTrue("v11 must stay exported as the migration's starting point", 11 in exportedVersions())

        val expected = openJdbc(newDbFile()).use { conn ->
            createRoomExpectedTables(conn)
            readSchema(conn)
        }
        val exported = schemaFrom(exportedStatements(declared))
        assertEquals(
            "schemas/$declared.json differs from what Room's compiler generates — re-export it",
            emptyList<String>(),
            diffSchemas(expected, exported),
        )
        assertEquals("tables", expected.keys.sorted(), exported.keys.sorted())
    }

    /**
     * The v11→v12 step, started from the COMMITTED v11 export rather than from a
     * reconstruction: this is the closest a JVM test gets to `MigrationTestHelper`
     * (which needs an instrumented device, and this project's whole migration
     * suite is deliberately device-free so CI gates on it).
     *
     * `runMigrations` runs the whole registered chain from 11, so the database it
     * leaves behind is at the DECLARED version — the 12.json comparison below is
     * therefore "every table 12 declared is still exactly as 12 declared it",
     * which is the property that matters: later steps may ADD, never reshape.
     */
    @Test
    fun theCommittedV11SchemaMigratesToTheCommittedV12Schema() {
        withMigratedDb(exportedStatements(11), fromVersion = 11) { conn ->
            assertSchemaMatchesRoomExpectation(conn, "committed schemas/11.json")
            assertEquals(
                "migrating past 12 must leave the committed 12.json tables untouched",
                emptyList<String>(),
                diffSchemas(schemaFrom(exportedStatements(12)), readSchema(conn), allowLaterAdditions = true),
            )
        }
    }

    /** The v12→v13 step, from the committed v12 export to the committed v13 one. */
    @Test
    fun theCommittedV12SchemaMigratesToTheCommittedV13Schema() {
        withMigratedDb(exportedStatements(12), fromVersion = 12) { conn ->
            assertSchemaMatchesRoomExpectation(conn, "committed schemas/12.json")
            assertEquals(
                "migrating 12→13 must reproduce the committed 13.json exactly",
                emptyList<String>(),
                diffSchemas(schemaFrom(exportedStatements(13)), readSchema(conn), allowLaterAdditions = true),
            )
        }
    }

    /** The v13→v14 step, from the committed v13 export to the committed v14 one. */
    @Test
    fun theCommittedV13SchemaMigratesToTheCommittedV14Schema() {
        withMigratedDb(exportedStatements(13), fromVersion = 13) { conn ->
            assertSchemaMatchesRoomExpectation(conn, "committed schemas/13.json")
            assertEquals(
                "migrating 13→14 must reproduce the committed 14.json exactly",
                emptyList<String>(),
                diffSchemas(schemaFrom(exportedStatements(14)), readSchema(conn), allowLaterAdditions = true),
            )
        }
    }

    /**
     * The kept-candidate table arrives empty, the config mirror gains its two
     * doc-id columns, and no existing row moves.
     *
     * The composite key is asserted against real SQLite rather than against the
     * entity declaration: `(vaultId, docId, medium, reason)` is what makes a
     * repeated identical refusal an UPDATE — without it, a medium serving bytes
     * this build refuses would add a doc-sized row on every single pass.
     */
    @Test
    fun theVaultDocCandidateMigrationIsPurelyAdditive() {
        val db = newDbFile()
        openJdbc(db).use { conn ->
            conn.applyAll(exportedStatements(13))
            conn.exec("PRAGMA user_version = 13")
            conn.applyAll(SAMPLE_ROWS_V7)
            val before = conn.rowCounts(COUNTED_TABLES)

            runMigrations(conn, from = 13)

            assertEquals("migration 13→14 must not touch a single user row", before, conn.rowCounts(COUNTED_TABLES))
            assertEquals(
                "`vault_doc_candidates` arrives empty",
                mapOf("vault_doc_candidates" to 0),
                conn.rowCounts(listOf("vault_doc_candidates")),
            )
            fun keep(reason: String) = conn.exec(
                "INSERT OR REPLACE INTO `vault_doc_candidates` (`vaultId`, `docId`, `medium`, `reason`, " +
                    "`docKind`, `docVersion`, `formatVersion`, `envelope`, `keptAtMs`) " +
                    "VALUES ('v1', 'd1', 'server', '$reason', 'portfolio', 3, 2, NULL, 1)",
            )
            keep("Corrupt.")
            keep("Corrupt.")
            assertEquals(
                "the same refusal at the same address is ONE candidate",
                mapOf("vault_doc_candidates" to 1),
                conn.rowCounts(listOf("vault_doc_candidates")),
            )
            keep("Foreign vault.")
            assertEquals(
                "a different refusal is a different candidate and must survive",
                mapOf("vault_doc_candidates" to 2),
                conn.rowCounts(listOf("vault_doc_candidates")),
            )
            // The two additive columns exist and read as "no address recorded"
            // — which the store treats as no directory, never as a doc id.
            conn.exec(
                "INSERT INTO `vaults` (`id`, `name`, `media`, `driveConnectionId`, `keyFingerprint`, " +
                    "`retirementProofPublicKey`, `createdAt`, `updatedAt`, `syncedAtMs`) " +
                    "VALUES ('v1', 'Household', 'server', NULL, 'f', 'k', '', '', 0)",
            )
            assertEquals("", conn.single("SELECT `headerDocId` FROM `vaults` LIMIT 1"))
            assertEquals("", conn.single("SELECT `commonDocId` FROM `vaults` LIMIT 1"))
        }
    }

    /**
     * The per-vault CAS cursor table arrives empty, and no existing row moves.
     *
     * The same shape as [theParanoidVaultMigrationIsPurelyAdditive], and for the
     * same reason: a schema step that touches user rows is the one kind of
     * migration bug that cannot be undone by shipping a fix.
     */
    @Test
    fun theVaultDocCursorMigrationIsPurelyAdditive() {
        val db = newDbFile()
        openJdbc(db).use { conn ->
            conn.applyAll(exportedStatements(12))
            conn.exec("PRAGMA user_version = 12")
            conn.applyAll(SAMPLE_ROWS_V7)
            val before = conn.rowCounts(COUNTED_TABLES)

            runMigrations(conn, from = 12)

            assertEquals("migration 12→13 must not touch a single user row", before, conn.rowCounts(COUNTED_TABLES))
            assertEquals(
                "`vault_doc_cursors` arrives empty",
                mapOf("vault_doc_cursors" to 0),
                conn.rowCounts(listOf("vault_doc_cursors")),
            )
            // The medium is part of the key, so one vault+doc can hold a row per
            // medium — the §6 rule, asserted against real SQLite rather than
            // against the entity declaration.
            listOf("server", "drive").forEach { medium ->
                conn.exec(
                    "INSERT INTO `vault_doc_cursors` (`vaultId`, `docId`, `medium`, `etag`, " +
                        "`docVersion`, `lastWriteId`, `syncedAtMs`) " +
                        "VALUES ('v1', 'd1', '$medium', '\"3\"', 3, 'w1', 0)",
                )
            }
            assertEquals(
                mapOf("vault_doc_cursors" to 2),
                conn.rowCounts(listOf("vault_doc_cursors")),
            )
        }
    }

    /** The two dormant tables arrive empty, and no existing row is touched. */
    @Test
    fun theParanoidVaultMigrationIsPurelyAdditive() {
        val db = newDbFile()
        openJdbc(db).use { conn ->
            conn.applyAll(exportedStatements(11))
            conn.exec("PRAGMA user_version = 11")
            conn.applyAll(SAMPLE_ROWS_V7)
            val before = conn.rowCounts(COUNTED_TABLES)

            runMigrations(conn, from = 11)

            assertEquals("migration 11→12 must not touch a single user row", before, conn.rowCounts(COUNTED_TABLES))
            assertEquals("`vaults` arrives empty", mapOf("vaults" to 0), conn.rowCounts(listOf("vaults")))
            assertEquals("`vault_docs` arrives empty", mapOf("vault_docs" to 0), conn.rowCounts(listOf("vault_docs")))
            // The membership columns exist and read as "not in a vault".
            assertEquals(null, conn.single("SELECT `vaultId` FROM `portfolios` LIMIT 1"))
            assertEquals(null, conn.single("SELECT `vaultAlias` FROM `portfolios` LIMIT 1"))
        }
    }

    private fun declaredVersion(): Int = roomOpenDelegate().let { delegate ->
        delegate.javaClass.getMethod("getVersion").apply { isAccessible = true }.invoke(delegate) as Int
    }

    private fun exportedSchemaDir(): File =
        listOf(File("schemas"), File("app/schemas")).firstOrNull { it.isDirectory }
            ?.resolve("at.bettertrack.app.data.db.BtDatabase")
            ?.takeIf { it.isDirectory }
            ?: error("exported Room schemas not found from ${File(".").absolutePath}")

    private fun exportedVersions(): List<Int> =
        exportedSchemaDir().listFiles().orEmpty()
            .mapNotNull { it.name.removeSuffix(".json").toIntOrNull() }
            .sorted()

    /** The `CREATE` statements Room itself wrote into `<version>.json`. */
    private fun exportedStatements(version: Int): List<String> {
        val file = exportedSchemaDir().resolve("$version.json")
        assertTrue("missing exported schema ${file.absolutePath}", file.isFile)
        val database = Json.parseToJsonElement(file.readText()).jsonObject["database"]!!.jsonObject
        return buildList {
            database["entities"]!!.jsonArray.forEach { entity ->
                val table = entity.jsonObject["tableName"]!!.jsonPrimitive.content
                fun sql(element: kotlinx.serialization.json.JsonElement) =
                    element.jsonObject["createSql"]!!.jsonPrimitive.content.replace("\${TABLE_NAME}", table)
                add(sql(entity))
                entity.jsonObject["indices"]?.jsonArray?.forEach { add(sql(it)) }
            }
        }
    }

    // ── Machinery ────────────────────────────────────────────────────────────

    private fun withMigratedDb(schema: List<String>, fromVersion: Int, assertions: (Connection) -> Unit) {
        openJdbc(newDbFile()).use { conn ->
            conn.applyAll(schema)
            conn.exec("PRAGMA user_version = $fromVersion")
            runMigrations(conn, from = fromVersion)
            assertions(conn)
        }
    }

    /** Runs the REAL [BtDatabase.MIGRATIONS] objects, in Room's own order. */
    private fun runMigrations(conn: Connection, from: Int) {
        val db = jdbcSupportDatabase(conn)
        BtDatabase.MIGRATIONS
            .filter { it.startVersion >= from }
            .sortedBy { it.startVersion }
            .forEach { migration ->
                check(migration.startVersion == conn.userVersion()) {
                    "chain broke: at v${conn.userVersion()} but next migration starts at ${migration.startVersion}"
                }
                migration.migrate(db)
                conn.exec("PRAGMA user_version = ${migration.endVersion}")
            }
    }

    /**
     * Two verdicts on the same database, because each catches what the other
     * cannot: Room's own `onValidateSchema` is the literal production check but
     * reports only the first table it dislikes, while the structural diff lists
     * every difference at once, which is what makes a failure here actionable.
     */
    private fun assertSchemaMatchesRoomExpectation(actualConn: Connection, what: String) {
        val expected = openJdbc(newDbFile()).use { expectedConn ->
            createRoomExpectedTables(expectedConn)
            readSchema(expectedConn)
        }
        val differences = diffSchemas(expected, readSchema(actualConn))
        assertEquals("$what: schema differs from the Room expectation", emptyList<String>(), differences)
        assertEquals("$what: Room's own validateMigration rejected the migrated database", "", roomValidationFailure(actualConn))
    }

    /** Runs the generated `onValidateSchema` — the exact code that throws on a real device. */
    private fun roomValidationFailure(conn: Connection): String {
        val delegate = roomOpenDelegate()
        val connectionType = Class.forName("androidx.sqlite.SQLiteConnection")
        val result = delegate.javaClass
            .getMethod("onValidateSchema", connectionType)
            .apply { isAccessible = true }
            .invoke(delegate, jdbcSqliteConnection(conn, connectionType))!!
        // ValidationResult exposes plain public fields, not getters.
        if (result.javaClass.getField("isValid").getBoolean(result)) return ""
        return result.javaClass.getField("expectedFoundMsg").get(result) as? String ?: "validation failed"
    }

    /**
     * Room's `TableInfo` rules, in list form. Notably it compares a DB-side
     * `DEFAULT` only where the `@Entity` declared one — an `ALTER TABLE … ADD
     * COLUMN … DEFAULT 0` leaves a default behind that a fresh `CREATE TABLE`
     * never has, and Room is right not to care. Tables Room does not know about
     * are ignored the same way; a missing one is not.
     */
    private fun diffSchemas(
        expected: Map<String, TableShape>,
        actual: Map<String, TableShape>,
        /**
         * Tolerate columns and indices the expectation does not know about.
         *
         * Only ever true when the EXPECTATION is a historical export: `runMigrations`
         * always walks to the declared version, so comparing the result against
         * (say) 12.json asks "is every table 12 declared still exactly as 12
         * declared it" — and a later purely-additive step must be allowed to have
         * added a column since. The comparison that actually protects production
         * is [assertSchemaMatchesRoomExpectation]'s, whose expectation is Room's
         * own `createAllTables`, and that one stays strict in both directions.
         */
        allowLaterAdditions: Boolean = false,
    ): List<String> = buildList {
        expected.forEach { (table, expectedShape) ->
            val actualShape = actual[table]
            if (actualShape == null) {
                add("table `$table` is missing")
                return@forEach
            }
            (expectedShape.columns.keys + actualShape.columns.keys).sorted().forEach { column ->
                val want = expectedShape.columns[column]
                val got = actualShape.columns[column]
                when {
                    want == null ->
                        if (!allowLaterAdditions) add("`$table`.`$column` exists but no entity declares it")
                    got == null -> add("`$table`.`$column` is missing")
                    else -> {
                        if (want.affinity != got.affinity) add("`$table`.`$column` affinity ${want.affinity} != ${got.affinity}")
                        if (want.notNull != got.notNull) add("`$table`.`$column` notNull ${want.notNull} != ${got.notNull}")
                        if (want.primaryKeyPosition != got.primaryKeyPosition) {
                            add("`$table`.`$column` primary-key position ${want.primaryKeyPosition} != ${got.primaryKeyPosition}")
                        }
                        if (want.defaultValue != null && want.defaultValue != got.defaultValue) {
                            add("`$table`.`$column` default ${want.defaultValue} != ${got.defaultValue}")
                        }
                    }
                }
            }
            (expectedShape.indices.keys + actualShape.indices.keys).sorted().forEach { index ->
                val want = expectedShape.indices[index]
                val got = actualShape.indices[index]
                when {
                    want == null ->
                        if (!allowLaterAdditions) add("`$table` has index `$index` that no entity declares")
                    got == null -> add("`$table` is missing index `$index`")
                    want != got -> add("`$table` index `$index` $want != $got")
                }
            }
        }
    }

    /**
     * The authoritative expectation: the generated `BtDatabase_Impl`'s own
     * `createAllTables`, invoked through a JDBC-backed `SQLiteConnection`.
     */
    private fun createRoomExpectedTables(conn: Connection) {
        val delegate = roomOpenDelegate()
        val connectionType = Class.forName("androidx.sqlite.SQLiteConnection")
        delegate.javaClass
            .getMethod("createAllTables", connectionType)
            .apply { isAccessible = true }
            .invoke(delegate, jdbcSqliteConnection(conn, connectionType))
    }

    private fun roomOpenDelegate(): Any {
        val implClass = Class.forName("at.bettertrack.app.data.db.BtDatabase_Impl")
        val impl = instantiateWithoutConstructor(implClass)
        return implClass.declaredMethods
            .first { it.name == "createOpenDelegate" && it.parameterCount == 0 }
            .apply { isAccessible = true }
            .invoke(impl)!!
    }

    /**
     * `BtDatabase_Impl` is only ever a bag of generated methods here — we call
     * one of them and throw it away — but its `RoomDatabase` supertype does real
     * work in its constructor. Allocating without running it keeps the test
     * independent of whatever `RoomDatabase` initialises today.
     */
    private fun instantiateWithoutConstructor(type: Class<*>): Any =
        runCatching { type.getDeclaredConstructor().apply { isAccessible = true }.newInstance() }
            .getOrElse {
                val unsafeField = Class.forName("sun.misc.Unsafe").getDeclaredField("theUnsafe").apply { isAccessible = true }
                val unsafe = unsafeField.get(null)
                unsafe.javaClass.getMethod("allocateInstance", Class::class.java).invoke(unsafe, type)!!
            }

    // ── JDBC ⇄ androidx.sqlite test doubles ──────────────────────────────────

    /** A [SupportSQLiteDatabase] that is really a JDBC connection. */
    private fun jdbcSupportDatabase(conn: Connection): SupportSQLiteDatabase =
        Proxy.newProxyInstance(
            SupportSQLiteDatabase::class.java.classLoader,
            arrayOf(SupportSQLiteDatabase::class.java),
        ) { _, method, args ->
            when (method.name) {
                "execSQL" -> conn.exec(args!![0] as String)
                "query" -> jdbcCursor(conn, args!![0] as String)
                "toString" -> "jdbc:SupportSQLiteDatabase"
                "hashCode" -> System.identityHashCode(conn)
                "equals" -> false
                else -> error(
                    "SupportSQLiteDatabase.${method.name}() is not implemented by this test double — " +
                        "a migration started using an API the JVM harness cannot execute.",
                )
            }
        } as SupportSQLiteDatabase

    /**
     * `androidx.sqlite.SQLiteConnection` over JDBC. Room's own `execSQL` helper
     * goes through `prepare(…).step()`, so the statement half has to be real
     * enough to run a PRAGMA and read its rows back.
     */
    private fun jdbcSqliteConnection(conn: Connection, connectionType: Class<*>): Any =
        Proxy.newProxyInstance(connectionType.classLoader, arrayOf(connectionType)) { _, method, args ->
            when (method.name) {
                "execSQL" -> conn.exec(args!![0] as String)
                "prepare" -> jdbcSqliteStatement(conn, args!![0] as String)
                "close" -> null
                "toString" -> "jdbc:SQLiteConnection"
                "hashCode" -> System.identityHashCode(conn)
                "equals" -> false
                else -> error("SQLiteConnection.${method.name}() is not implemented by this test double")
            }
        }

    /** `androidx.sqlite.SQLiteStatement` over JDBC — 0-based reads, as androidx defines them. */
    private fun jdbcSqliteStatement(conn: Connection, sql: String): Any {
        val statementType = Class.forName("androidx.sqlite.SQLiteStatement")
        val statement = conn.createStatement()
        var rs: java.sql.ResultSet? = null
        var names: List<String> = emptyList()
        return Proxy.newProxyInstance(statementType.classLoader, arrayOf(statementType)) { _, method, args ->
            fun index() = (args!![0] as Int) + 1
            when (method.name) {
                "step" -> {
                    if (rs == null) {
                        val hasResults = statement.execute(sql)
                        if (hasResults) {
                            rs = statement.resultSet
                            names = rs!!.metaData.let { md -> (1..md.columnCount).map { md.getColumnName(it) } }
                        }
                    }
                    rs?.next() ?: false
                }
                "getColumnCount" -> names.size
                "getColumnName" -> names[args!![0] as Int]
                "getColumnNames" -> names
                "getText" -> rs!!.getString(index()).orEmpty()
                "getLong" -> rs!!.getLong(index())
                "getDouble" -> rs!!.getDouble(index())
                "getBlob" -> rs!!.getBytes(index()) ?: ByteArray(0)
                "isNull" -> rs!!.getObject(index()) == null
                "getColumnType" -> when (rs!!.getObject(index())) {
                    null -> 5 // SQLITE_NULL
                    is Int, is Long -> 1 // SQLITE_INTEGER
                    is Double, is Float -> 2 // SQLITE_FLOAT
                    is ByteArray -> 4 // SQLITE_BLOB
                    else -> 3 // SQLITE_TEXT
                }
                "reset", "clearBindings" -> null
                "close" -> { rs?.close(); statement.close(); null }
                "toString" -> "jdbc:SQLiteStatement"
                "hashCode" -> System.identityHashCode(statement)
                "equals" -> false
                else -> error("SQLiteStatement.${method.name}() is not implemented by this test double")
            }
        }
    }

    /** Android's [Cursor] over a JDBC `ResultSet` — the columns Room's PRAGMA reads need. */
    private fun jdbcCursor(conn: Connection, sql: String): Cursor {
        val statement = conn.createStatement()
        val rs = statement.executeQuery(sql)
        val names = rs.metaData.let { md -> (1..md.columnCount).map { md.getColumnName(it) } }
        return Proxy.newProxyInstance(Cursor::class.java.classLoader, arrayOf(Cursor::class.java)) { _, method, args ->
            when (method.name) {
                "getColumnIndex" -> names.indexOf(args!![0] as String)
                "getColumnCount" -> names.size
                "getColumnName" -> names[args!![0] as Int]
                "moveToNext" -> rs.next()
                "getString" -> rs.getString((args!![0] as Int) + 1)
                "getInt" -> rs.getInt((args!![0] as Int) + 1)
                "getLong" -> rs.getLong((args!![0] as Int) + 1)
                "isNull" -> rs.getObject((args!![0] as Int) + 1) == null
                "close" -> { rs.close(); statement.close(); null }
                "toString" -> "jdbc:Cursor"
                "hashCode" -> System.identityHashCode(rs)
                "equals" -> false
                else -> error("Cursor.${method.name}() is not implemented by this test double")
            }
        } as Cursor
    }

    // ── Room's TableInfo comparison, reimplemented over PRAGMA ───────────────

    private data class ColumnShape(
        val affinity: String,
        val notNull: Boolean,
        val primaryKeyPosition: Int,
        val defaultValue: String?,
    )

    private data class IndexShape(val unique: Boolean, val columns: List<String>)

    private data class TableShape(
        val columns: Map<String, ColumnShape>,
        val indices: Map<String, IndexShape>,
    )

    /** Builds a scratch database from [statements] purely to read its shape. */
    private fun schemaFrom(statements: List<String>): Map<String, TableShape> =
        openJdbc(newDbFile()).use { conn ->
            conn.applyAll(statements)
            readSchema(conn)
        }

    private fun readSchema(conn: Connection): Map<String, TableShape> {
        val tables = conn.list(
            "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' " +
                "AND name NOT IN ('room_master_table', 'android_metadata')",
        )
        return tables.associateWith { table ->
            val columns = mutableMapOf<String, ColumnShape>()
            conn.createStatement().use { st ->
                st.executeQuery("PRAGMA table_info(`$table`)").use { rs ->
                    while (rs.next()) {
                        columns[rs.getString("name")] = ColumnShape(
                            affinity = affinityOf(rs.getString("type")),
                            notNull = rs.getInt("notnull") != 0,
                            primaryKeyPosition = rs.getInt("pk"),
                            defaultValue = rs.getString("dflt_value"),
                        )
                    }
                }
            }
            val indices = mutableMapOf<String, IndexShape>()
            val indexRows = mutableListOf<Pair<String, Boolean>>()
            conn.createStatement().use { st ->
                st.executeQuery("PRAGMA index_list(`$table`)").use { rs ->
                    // Room reads only the indices it could have created itself.
                    while (rs.next()) {
                        val name = rs.getString("name")
                        if (name.startsWith("index_")) indexRows += name to (rs.getInt("unique") != 0)
                    }
                }
            }
            indexRows.forEach { (name, unique) ->
                indices[name] = IndexShape(unique, conn.list("PRAGMA index_info(`$name`)", column = "name"))
            }
            TableShape(columns, indices)
        }
    }

    /**
     * Room compares a column's type AFFINITY, and its default value only when the
     * `@Entity` declared one — so the shapes are normalised the same way before
     * they are compared. See `androidx.room.util.TableInfo`.
     */
    private fun affinityOf(declaredType: String?): String {
        val type = declaredType?.uppercase().orEmpty()
        return when {
            type.isEmpty() -> "BLOB"
            type.contains("INT") -> "INTEGER"
            type.contains("CHAR") || type.contains("CLOB") || type.contains("TEXT") -> "TEXT"
            type.contains("BLOB") -> "BLOB"
            type.contains("REAL") || type.contains("FLOA") || type.contains("DOUB") -> "REAL"
            else -> "NUMERIC"
        }
    }

    // ── Tiny JDBC helpers ────────────────────────────────────────────────────

    private fun newDbFile(): File =
        File(Files.createTempDirectory("bt-migration").toFile(), "bettertrack.db").also { it.deleteOnExit() }

    private fun openJdbc(file: File): Connection = DriverManager.getConnection("jdbc:sqlite:${file.absolutePath}")

    private fun Connection.exec(sql: String): Any? {
        createStatement().use { it.execute(sql) }
        return null
    }

    private fun Connection.applyAll(statements: List<String>) = statements.forEach { exec(it) }

    private fun Connection.userVersion(): Int =
        createStatement().use { st ->
            st.executeQuery("PRAGMA user_version").use { it.next(); it.getInt(1) }
        }

    private fun Connection.list(sql: String, column: String = "name"): List<String> =
        createStatement().use { st ->
            st.executeQuery(sql).use { rs ->
                buildList { while (rs.next()) add(rs.getString(column)) }
            }
        }

    private fun Connection.single(sql: String): String? =
        createStatement().use { st -> st.executeQuery(sql).use { if (it.next()) it.getString(1) else null } }

    private fun Connection.rowCounts(tables: List<String>): Map<String, Int> =
        tables.associateWith { table ->
            createStatement().use { st ->
                st.executeQuery("SELECT COUNT(*) FROM `$table`").use { it.next(); it.getInt(1) }
            }
        }

    private companion object {

        val COUNTED_TABLES = listOf(
            "portfolios", "holdings", "transactions", "cash_sources",
            "cash_movements", "custom_assets", "sync_ops", "meta",
        )

        // ── v3 baseline — rev 8ae4751 (`@Database(version = 3)`) ─────────────
        // Every table the app has ever had except the four the later migrations
        // create. Read off the @Entity definitions at that rev.
        val SCHEMA_V3 = listOf(
            "CREATE TABLE `portfolios` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, `visibility` TEXT NOT NULL, " +
                "`sortOrder` INTEGER NOT NULL, `isDefault` INTEGER NOT NULL, `defaultPayFromCash` INTEGER NOT NULL, " +
                "`archivedAt` TEXT, `baseCurrency` TEXT, `detailSyncedAtMs` INTEGER, `totals_marketValueEur` REAL, " +
                "`totals_investedEur` REAL, `totals_unrealizedPnlEur` REAL, `totals_unrealizedPnlPct` REAL, " +
                "`totals_dayChangeEur` REAL, `totals_dayChangePct` REAL, `totals_cashEur` REAL, " +
                "`totals_totalValueEur` REAL, PRIMARY KEY(`id`))",
            "CREATE TABLE `holdings` (`portfolioId` TEXT NOT NULL, `assetId` TEXT NOT NULL, `assetSymbol` TEXT NOT NULL, " +
                "`assetName` TEXT NOT NULL, `assetExchange` TEXT, `assetCurrency` TEXT NOT NULL, `assetType` TEXT NOT NULL, " +
                "`assetIsCustom` INTEGER NOT NULL, `quantity` REAL NOT NULL, `avgCost` REAL NOT NULL, " +
                "`realizedPnl` REAL NOT NULL, `price` REAL, `marketValueEur` REAL, `costBasisEur` REAL, " +
                "`unrealizedPnlEur` REAL, `unrealizedPnlPct` REAL, `dayChangeEur` REAL, `dayChangePct` REAL, " +
                "PRIMARY KEY(`portfolioId`, `assetId`))",
            "CREATE INDEX `index_holdings_portfolioId` ON `holdings` (`portfolioId`)",
            "CREATE TABLE `transactions` (`id` TEXT NOT NULL, `portfolioId` TEXT NOT NULL, `assetId` TEXT NOT NULL, " +
                "`side` TEXT NOT NULL, `quantity` REAL NOT NULL, `price` REAL NOT NULL, `fee` REAL NOT NULL, " +
                "`executedAt` TEXT NOT NULL, `executedAtMs` INTEGER NOT NULL, `note` TEXT, `assetSymbol` TEXT NOT NULL, " +
                "`assetName` TEXT NOT NULL, `assetExchange` TEXT, `assetCurrency` TEXT NOT NULL, `assetType` TEXT NOT NULL, " +
                "`assetIsCustom` INTEGER NOT NULL, PRIMARY KEY(`id`))",
            "CREATE INDEX `index_transactions_portfolioId` ON `transactions` (`portfolioId`)",
            "CREATE INDEX `index_transactions_portfolioId_executedAtMs` ON `transactions` (`portfolioId`, `executedAtMs`)",
            "CREATE TABLE `portfolio_history` (`portfolioId` TEXT NOT NULL, `range` TEXT NOT NULL, " +
                "`baseCurrency` TEXT NOT NULL, `pointsJson` TEXT NOT NULL, `performanceJson` TEXT NOT NULL, " +
                "`syncedAtMs` INTEGER NOT NULL, PRIMARY KEY(`portfolioId`, `range`))",
            "CREATE TABLE `cash_sources` (`id` TEXT NOT NULL, `portfolioId` TEXT NOT NULL, `name` TEXT NOT NULL, " +
                "`kind` TEXT NOT NULL, `isMain` INTEGER NOT NULL, `balanceEur` REAL NOT NULL, `archivedAt` TEXT, " +
                "PRIMARY KEY(`id`))",
            "CREATE INDEX `index_cash_sources_portfolioId` ON `cash_sources` (`portfolioId`)",
            "CREATE TABLE `cash_movements` (`id` TEXT NOT NULL, `portfolioId` TEXT NOT NULL, `sourceId` TEXT NOT NULL, " +
                "`kind` TEXT NOT NULL, `amountEur` REAL NOT NULL, `transactionId` TEXT, `transferId` TEXT, " +
                "`counterpartSourceId` TEXT, `executedAt` TEXT NOT NULL, `executedAtMs` INTEGER NOT NULL, `note` TEXT, " +
                "`createdAt` TEXT NOT NULL, PRIMARY KEY(`id`))",
            "CREATE INDEX `index_cash_movements_portfolioId` ON `cash_movements` (`portfolioId`)",
            "CREATE INDEX `index_cash_movements_portfolioId_executedAtMs` ON `cash_movements` (`portfolioId`, `executedAtMs`)",
            "CREATE TABLE `custom_assets` (`id` TEXT NOT NULL, `symbol` TEXT NOT NULL, `name` TEXT NOT NULL, " +
                "`category` TEXT, `currency` TEXT NOT NULL, PRIMARY KEY(`id`))",
            "CREATE TABLE `custom_asset_value_points` (`assetId` TEXT NOT NULL, `date` TEXT NOT NULL, " +
                "`value` REAL NOT NULL, PRIMARY KEY(`assetId`, `date`))",
            "CREATE INDEX `index_custom_asset_value_points_assetId` ON `custom_asset_value_points` (`assetId`)",
            "CREATE TABLE `watchlists` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, `isDefault` INTEGER NOT NULL, " +
                "`sortOrder` INTEGER NOT NULL, PRIMARY KEY(`id`))",
            "CREATE TABLE `watchlist_items` (`id` TEXT NOT NULL, `watchlistId` TEXT NOT NULL, `assetId` TEXT NOT NULL, " +
                "`sortOrder` INTEGER NOT NULL, `note` TEXT, `assetSymbol` TEXT NOT NULL, `assetName` TEXT NOT NULL, " +
                "`assetExchange` TEXT, `assetCurrency` TEXT NOT NULL, `assetType` TEXT NOT NULL, PRIMARY KEY(`id`))",
            "CREATE INDEX `index_watchlist_items_watchlistId` ON `watchlist_items` (`watchlistId`)",
            "CREATE TABLE `conglomerates` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, `description` TEXT, " +
                "`status` TEXT NOT NULL, `visibility` TEXT NOT NULL, `positionCount` INTEGER NOT NULL, " +
                "`createdAt` TEXT NOT NULL, `updatedAt` TEXT NOT NULL, PRIMARY KEY(`id`))",
            "CREATE TABLE `conglomerate_positions` (`conglomerateId` TEXT NOT NULL, `assetId` TEXT NOT NULL, " +
                "`weightPct` REAL NOT NULL, `sortOrder` INTEGER NOT NULL, `assetSymbol` TEXT NOT NULL, " +
                "`assetName` TEXT NOT NULL, `assetCurrency` TEXT NOT NULL, `assetType` TEXT NOT NULL, " +
                "PRIMARY KEY(`conglomerateId`, `assetId`))",
            "CREATE INDEX `index_conglomerate_positions_conglomerateId` ON `conglomerate_positions` (`conglomerateId`)",
            "CREATE TABLE `sync_ops` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `clientId` TEXT NOT NULL, " +
                "`opType` TEXT NOT NULL, `portfolioId` TEXT, `payloadJson` TEXT NOT NULL, `status` TEXT NOT NULL, " +
                "`attemptCount` INTEGER NOT NULL, `nextAttemptAtMs` INTEGER NOT NULL, `serverError` TEXT, " +
                "`serverResultJson` TEXT, `accountKey` TEXT NOT NULL, `createdAtMs` INTEGER NOT NULL, " +
                "`updatedAtMs` INTEGER NOT NULL)",
            "CREATE UNIQUE INDEX `index_sync_ops_clientId` ON `sync_ops` (`clientId`)",
            "CREATE INDEX `index_sync_ops_status` ON `sync_ops` (`status`)",
            "CREATE TABLE `meta` (`key` TEXT NOT NULL, `value` TEXT NOT NULL, PRIMARY KEY(`key`))",
        )

        /** v1 had no `portfolio_history` and no transfer columns (see MIGRATION_1_2 / 2_3). */
        val SCHEMA_V1 = SCHEMA_V3
            .filterNot { it.contains("`portfolio_history`") }
            .map { it.replace("`transferId` TEXT, `counterpartSourceId` TEXT, ", "") }

        /** v2 = v1 plus the history cache. */
        val SCHEMA_V2 = SCHEMA_V3.map { it.replace("`transferId` TEXT, `counterpartSourceId` TEXT, ", "") }

        // ── Forward deltas, each labelled with the rev that shipped it ───────
        /** rev f9b60e0 — `@Database(version = 4)`. */
        val DELTA_SMOOTHING = listOf(
            "ALTER TABLE `custom_assets` ADD COLUMN `smoothing` INTEGER NOT NULL DEFAULT 0",
        )

        /** rev 3a8ca5f (no version bump) / rev fe3b45f's MIGRATION_4_5 — `version = 5`. */
        val DELTA_FIRST_ATTEMPT_AT_MS = listOf(
            "ALTER TABLE `sync_ops` ADD COLUMN `firstAttemptAtMs` INTEGER NOT NULL DEFAULT 0",
        )

        /** rev fe3b45f — `@Database(version = 6)`: v5 provenance + mirrorchain overlays. */
        val DELTA_PROVENANCE_AND_MIRROR = listOf(
            "ALTER TABLE `cash_movements` ADD COLUMN `source` TEXT NOT NULL DEFAULT 'manual'",
            "ALTER TABLE `cash_movements` ADD COLUMN `dividendId` TEXT",
            "ALTER TABLE `cash_movements` ADD COLUMN `mirrorId` TEXT",
            "ALTER TABLE `cash_movements` ADD COLUMN `mirrorVersion` INTEGER",
            "ALTER TABLE `cash_movements` ADD COLUMN `mirrorAddedByName` TEXT",
            "ALTER TABLE `cash_movements` ADD COLUMN `mirrorAddedByIcon` TEXT",
            "ALTER TABLE `transactions` ADD COLUMN `source` TEXT NOT NULL DEFAULT 'manual'",
            "ALTER TABLE `transactions` ADD COLUMN `mirrorId` TEXT",
            "ALTER TABLE `transactions` ADD COLUMN `mirrorVersion` INTEGER",
            "ALTER TABLE `transactions` ADD COLUMN `mirrorAddedByName` TEXT",
            "ALTER TABLE `transactions` ADD COLUMN `mirrorAddedByIcon` TEXT",
            "ALTER TABLE `portfolios` ADD COLUMN `mirrorChainId` TEXT",
            "ALTER TABLE `portfolios` ADD COLUMN `mirrorChainName` TEXT",
            "ALTER TABLE `portfolios` ADD COLUMN `mirrorRole` TEXT",
            "ALTER TABLE `portfolios` ADD COLUMN `mirrorMemberCount` INTEGER",
            "ALTER TABLE `portfolios` ADD COLUMN `mirrorSyncPercent` INTEGER",
            "ALTER TABLE `portfolios` ADD COLUMN `mirrorSynced` INTEGER",
        )

        /** rev 4b24c6c — `@Database(version = 7)`: the storage-mode routing tag. */
        val DELTA_BACKEND_TAG = listOf(
            "ALTER TABLE `sync_ops` ADD COLUMN `backendTag` TEXT NOT NULL DEFAULT 'server'",
        )

        /** rev 8da07e1 — `@Database(version = 8)`: cash classification. */
        val DELTA_CASH_TAGS = listOf(
            "ALTER TABLE `cash_movements` ADD COLUMN `tagIds` TEXT NOT NULL DEFAULT ''",
            "CREATE TABLE `cash_tags` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, `color` TEXT NOT NULL, " +
                "`system` INTEGER NOT NULL, `systemKey` TEXT, PRIMARY KEY(`id`))",
        )

        /** rev ac316e1 as `version = 8`, rev 1f48aef renumbered to `version = 9`: the Drive-mode store. */
        val DELTA_VAULT_TABLES = listOf(
            "CREATE TABLE `vault_entities` (`kind` TEXT NOT NULL, `id` TEXT NOT NULL, `rev` INTEGER NOT NULL, " +
                "`editedAt` TEXT NOT NULL, `editedBy` TEXT NOT NULL, `deletedAt` TEXT, `dataJson` TEXT NOT NULL, " +
                "PRIMARY KEY(`kind`, `id`))",
            "CREATE INDEX `index_vault_entities_kind` ON `vault_entities` (`kind`)",
            "CREATE TABLE `vault_meta` (`key` TEXT NOT NULL, `value` TEXT, PRIMARY KEY(`key`))",
            "CREATE TABLE `price_cache` (`assetId` TEXT NOT NULL, `date` TEXT NOT NULL, `close` REAL NOT NULL, " +
                "`currency` TEXT NOT NULL, `syncedAtMs` INTEGER NOT NULL, PRIMARY KEY(`assetId`, `date`))",
            "CREATE INDEX `index_price_cache_assetId` ON `price_cache` (`assetId`)",
        )

        /** rev 6f0a3ea — `@Database(version = 10)`: the parked-op reason code. */
        val DELTA_SYNC_ERROR_CODE = listOf(
            "ALTER TABLE `sync_ops` ADD COLUMN `errorCode` TEXT",
        )

        /** rev 8adf20a — `@Database(version = 11)`: the portfolio icon becomes a server field. */
        val DELTA_PORTFOLIO_KIND = listOf(
            "ALTER TABLE `portfolios` ADD COLUMN `kind` TEXT",
        )

        val SCHEMA_V4 = SCHEMA_V3 + DELTA_SMOOTHING
        val SCHEMA_V5 = SCHEMA_V4 + DELTA_FIRST_ATTEMPT_AT_MS
        val SCHEMA_V6 = SCHEMA_V5 + DELTA_PROVENANCE_AND_MIRROR
        val SCHEMA_V7 = SCHEMA_V6 + DELTA_BACKEND_TAG
        val SCHEMA_V8 = SCHEMA_V7 + DELTA_CASH_TAGS
        val SCHEMA_V9 = SCHEMA_V8 + DELTA_VAULT_TABLES
        val SCHEMA_V10 = SCHEMA_V9 + DELTA_SYNC_ERROR_CODE
        val SCHEMA_V11 = SCHEMA_V10 + DELTA_PORTFOLIO_KIND

        val HISTORICAL_SCHEMAS = listOf(
            1 to SCHEMA_V1,
            2 to SCHEMA_V2,
            3 to SCHEMA_V3,
            4 to SCHEMA_V4,
            5 to SCHEMA_V5,
            6 to SCHEMA_V6,
            7 to SCHEMA_V7,
            8 to SCHEMA_V8,
            9 to SCHEMA_V9,
            10 to SCHEMA_V10,
            11 to SCHEMA_V11,
        )

        /**
         * `sqlite3 .schema` of the OWNER'S PHONE, pulled over adb on 2026-08-05
         * with the database at `user_version = 7`. Transcribed verbatim; the
         * `android_metadata`, `sqlite_sequence` and `room_master_table` rows are
         * omitted because Room creates or ignores them itself. No user data here.
         */
        val SCHEMA_V7_OWNER_DEVICE = listOf(
            "CREATE TABLE `portfolios` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, `visibility` TEXT NOT NULL, `sortOrder` INTEGER NOT NULL, `isDefault` INTEGER NOT NULL, `defaultPayFromCash` INTEGER NOT NULL, `archivedAt` TEXT, `baseCurrency` TEXT, `detailSyncedAtMs` INTEGER, `totals_marketValueEur` REAL, `totals_investedEur` REAL, `totals_unrealizedPnlEur` REAL, `totals_unrealizedPnlPct` REAL, `totals_dayChangeEur` REAL, `totals_dayChangePct` REAL, `totals_cashEur` REAL, `totals_totalValueEur` REAL, `mirrorChainId` TEXT, `mirrorChainName` TEXT, `mirrorRole` TEXT, `mirrorMemberCount` INTEGER, `mirrorSyncPercent` INTEGER, `mirrorSynced` INTEGER, PRIMARY KEY(`id`))",
            "CREATE TABLE `holdings` (`portfolioId` TEXT NOT NULL, `assetId` TEXT NOT NULL, `assetSymbol` TEXT NOT NULL, `assetName` TEXT NOT NULL, `assetExchange` TEXT, `assetCurrency` TEXT NOT NULL, `assetType` TEXT NOT NULL, `assetIsCustom` INTEGER NOT NULL, `quantity` REAL NOT NULL, `avgCost` REAL NOT NULL, `realizedPnl` REAL NOT NULL, `price` REAL, `marketValueEur` REAL, `costBasisEur` REAL, `unrealizedPnlEur` REAL, `unrealizedPnlPct` REAL, `dayChangeEur` REAL, `dayChangePct` REAL, PRIMARY KEY(`portfolioId`, `assetId`))",
            "CREATE TABLE `transactions` (`id` TEXT NOT NULL, `portfolioId` TEXT NOT NULL, `assetId` TEXT NOT NULL, `side` TEXT NOT NULL, `quantity` REAL NOT NULL, `price` REAL NOT NULL, `fee` REAL NOT NULL, `executedAt` TEXT NOT NULL, `executedAtMs` INTEGER NOT NULL, `note` TEXT, `assetSymbol` TEXT NOT NULL, `assetName` TEXT NOT NULL, `assetExchange` TEXT, `assetCurrency` TEXT NOT NULL, `assetType` TEXT NOT NULL, `assetIsCustom` INTEGER NOT NULL, `source` TEXT NOT NULL DEFAULT 'manual', `mirrorId` TEXT, `mirrorVersion` INTEGER, `mirrorAddedByName` TEXT, `mirrorAddedByIcon` TEXT, PRIMARY KEY(`id`))",
            "CREATE TABLE `portfolio_history` (`portfolioId` TEXT NOT NULL, `range` TEXT NOT NULL, `baseCurrency` TEXT NOT NULL, `pointsJson` TEXT NOT NULL, `performanceJson` TEXT NOT NULL, `syncedAtMs` INTEGER NOT NULL, PRIMARY KEY(`portfolioId`, `range`))",
            "CREATE TABLE `cash_sources` (`id` TEXT NOT NULL, `portfolioId` TEXT NOT NULL, `name` TEXT NOT NULL, `kind` TEXT NOT NULL, `isMain` INTEGER NOT NULL, `balanceEur` REAL NOT NULL, `archivedAt` TEXT, PRIMARY KEY(`id`))",
            "CREATE TABLE `cash_movements` (`id` TEXT NOT NULL, `portfolioId` TEXT NOT NULL, `sourceId` TEXT NOT NULL, `kind` TEXT NOT NULL, `amountEur` REAL NOT NULL, `transactionId` TEXT, `transferId` TEXT, `counterpartSourceId` TEXT, `executedAt` TEXT NOT NULL, `executedAtMs` INTEGER NOT NULL, `note` TEXT, `createdAt` TEXT NOT NULL, `source` TEXT NOT NULL DEFAULT 'manual', `dividendId` TEXT, `mirrorId` TEXT, `mirrorVersion` INTEGER, `mirrorAddedByName` TEXT, `mirrorAddedByIcon` TEXT, PRIMARY KEY(`id`))",
            "CREATE TABLE `custom_assets` (`id` TEXT NOT NULL, `symbol` TEXT NOT NULL, `name` TEXT NOT NULL, `category` TEXT, `currency` TEXT NOT NULL, `smoothing` INTEGER NOT NULL, PRIMARY KEY(`id`))",
            "CREATE TABLE `custom_asset_value_points` (`assetId` TEXT NOT NULL, `date` TEXT NOT NULL, `value` REAL NOT NULL, PRIMARY KEY(`assetId`, `date`))",
            "CREATE TABLE `watchlists` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, `isDefault` INTEGER NOT NULL, `sortOrder` INTEGER NOT NULL, PRIMARY KEY(`id`))",
            "CREATE TABLE `watchlist_items` (`id` TEXT NOT NULL, `watchlistId` TEXT NOT NULL, `assetId` TEXT NOT NULL, `sortOrder` INTEGER NOT NULL, `note` TEXT, `assetSymbol` TEXT NOT NULL, `assetName` TEXT NOT NULL, `assetExchange` TEXT, `assetCurrency` TEXT NOT NULL, `assetType` TEXT NOT NULL, PRIMARY KEY(`id`))",
            "CREATE TABLE `conglomerates` (`id` TEXT NOT NULL, `name` TEXT NOT NULL, `description` TEXT, `status` TEXT NOT NULL, `visibility` TEXT NOT NULL, `positionCount` INTEGER NOT NULL, `createdAt` TEXT NOT NULL, `updatedAt` TEXT NOT NULL, PRIMARY KEY(`id`))",
            "CREATE TABLE `conglomerate_positions` (`conglomerateId` TEXT NOT NULL, `assetId` TEXT NOT NULL, `weightPct` REAL NOT NULL, `sortOrder` INTEGER NOT NULL, `assetSymbol` TEXT NOT NULL, `assetName` TEXT NOT NULL, `assetCurrency` TEXT NOT NULL, `assetType` TEXT NOT NULL, PRIMARY KEY(`conglomerateId`, `assetId`))",
            "CREATE TABLE `sync_ops` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `clientId` TEXT NOT NULL, `opType` TEXT NOT NULL, `portfolioId` TEXT, `payloadJson` TEXT NOT NULL, `status` TEXT NOT NULL, `attemptCount` INTEGER NOT NULL, `nextAttemptAtMs` INTEGER NOT NULL, `serverError` TEXT, `serverResultJson` TEXT, `accountKey` TEXT NOT NULL, `createdAtMs` INTEGER NOT NULL, `updatedAtMs` INTEGER NOT NULL, `firstAttemptAtMs` INTEGER NOT NULL DEFAULT 0, `backendTag` TEXT NOT NULL DEFAULT 'server')",
            "CREATE TABLE `meta` (`key` TEXT NOT NULL, `value` TEXT NOT NULL, PRIMARY KEY(`key`))",
            "CREATE INDEX `index_holdings_portfolioId` ON `holdings` (`portfolioId`)",
            "CREATE INDEX `index_transactions_portfolioId` ON `transactions` (`portfolioId`)",
            "CREATE INDEX `index_transactions_portfolioId_executedAtMs` ON `transactions` (`portfolioId`, `executedAtMs`)",
            "CREATE INDEX `index_cash_sources_portfolioId` ON `cash_sources` (`portfolioId`)",
            "CREATE INDEX `index_cash_movements_portfolioId` ON `cash_movements` (`portfolioId`)",
            "CREATE INDEX `index_cash_movements_portfolioId_executedAtMs` ON `cash_movements` (`portfolioId`, `executedAtMs`)",
            "CREATE INDEX `index_custom_asset_value_points_assetId` ON `custom_asset_value_points` (`assetId`)",
            "CREATE INDEX `index_watchlist_items_watchlistId` ON `watchlist_items` (`watchlistId`)",
            "CREATE INDEX `index_conglomerate_positions_conglomerateId` ON `conglomerate_positions` (`conglomerateId`)",
            "CREATE UNIQUE INDEX `index_sync_ops_clientId` ON `sync_ops` (`clientId`)",
            "CREATE INDEX `index_sync_ops_status` ON `sync_ops` (`status`)",
        )

        /**
         * Synthetic rows shaped like the ones on the owner's phone — a parked and
         * a drained sync op, a mirrorchain-sourced cash movement, a dividend —
         * so the migration is exercised against populated tables. Values are
         * invented; only the SHAPES come from the device.
         */
        val SAMPLE_ROWS_V7 = listOf(
            "INSERT INTO `portfolios` (`id`, `name`, `visibility`, `sortOrder`, `isDefault`, `defaultPayFromCash`) " +
                "VALUES ('p1', 'Main', 'private', 0, 1, 1)",
            "INSERT INTO `holdings` (`portfolioId`, `assetId`, `assetSymbol`, `assetName`, `assetCurrency`, " +
                "`assetType`, `assetIsCustom`, `quantity`, `avgCost`, `realizedPnl`) " +
                "VALUES ('p1', 'a1', 'ACME', 'Acme Inc', 'EUR', 'stock', 0, 1.0, 1.0, 0.0)",
            "INSERT INTO `transactions` (`id`, `portfolioId`, `assetId`, `side`, `quantity`, `price`, `fee`, " +
                "`executedAt`, `executedAtMs`, `assetSymbol`, `assetName`, `assetCurrency`, `assetType`, `assetIsCustom`) " +
                "VALUES ('t1', 'p1', 'a1', 'buy', 1.0, 1.0, 0.0, '2026-07-01T00:00:00Z', 1782950400000, " +
                "'ACME', 'Acme Inc', 'EUR', 'stock', 0)",
            "INSERT INTO `cash_sources` (`id`, `portfolioId`, `name`, `kind`, `isMain`, `balanceEur`) " +
                "VALUES ('s1', 'p1', 'Main', 'bank', 1, 100.0)",
            "INSERT INTO `cash_movements` (`id`, `portfolioId`, `sourceId`, `kind`, `amountEur`, `executedAt`, " +
                "`executedAtMs`, `createdAt`, `source`) " +
                "VALUES ('c1', 'p1', 's1', 'dividend', 3.5, '2026-07-01T00:00:00Z', 1782950400000, " +
                "'2026-07-01T00:00:00Z', 'sync:mirrorchain')",
            "INSERT INTO `custom_assets` (`id`, `symbol`, `name`, `currency`, `smoothing`) " +
                "VALUES ('ca1', 'HOUSE', 'House', 'EUR', 0)",
            "INSERT INTO `sync_ops` (`clientId`, `opType`, `payloadJson`, `status`, `attemptCount`, " +
                "`nextAttemptAtMs`, `accountKey`, `createdAtMs`, `updatedAtMs`, `firstAttemptAtMs`, `backendTag`) " +
                "VALUES ('4515a384-775a-4ce9-bffb-b1a5f8380e83', 'cash_fee', '{\"amountEur\":3.5}', 'done', 0, 0, " +
                "'owner', 1785831404281, 1785831404281, 1785831404281, 'server')",
            "INSERT INTO `sync_ops` (`clientId`, `opType`, `payloadJson`, `status`, `attemptCount`, " +
                "`nextAttemptAtMs`, `serverError`, `accountKey`, `createdAtMs`, `updatedAtMs`, `firstAttemptAtMs`, " +
                "`backendTag`) VALUES ('2baf3d2b-3782-4b2d-8188-ec1f07a41162', 'tx_buy', '{\"side\":\"buy\"}', " +
                "'in_flight', 1, 0, 'Something went wrong', 'owner', 1785834462602, 1785834462602, 0, 'server')",
            "INSERT INTO `meta` (`key`, `value`) VALUES ('owner_account_key', 'owner')",
        )
    }
}
