package at.bettertrack.app.data.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

/**
 * The BetterTrack local database (spec §7.1) — the display source of truth for
 * everything portfolio-scoped, plus the durable outbound sync queue (§7.3).
 * The DB holds exactly ONE account's data (owner key in [MetaEntity]); logout
 * and account-switch wipe it in full via [clearAllTables].
 *
 * Migrations are REAL (not destructive) from v1 on: the sync queue is durable
 * user data — an app update must never drop queued ledger events.
 *
 * ## KMP/iOS port (Phase 2), source set narrowed in the web port (Phase W0)
 *
 * The `@Database` declaration, its 18 entities and 13 DAOs live in the `dbMain`
 * source set so BOTH the Android app and the iOS app compile the SAME schema
 * from the SAME source. `dbMain` sits between commonMain and {android, ios}
 * rather than being commonMain itself because Room publishes NO wasmJs artifact
 * (room-runtime 2.8.4 ships android/jvm/native only), so the browser target must
 * not see this file at all — see the `dbMain` note in shared/build.gradle.kts. Construction is source-set-specific: the ANDROID factory keeps the
 * exact historical migration chain (see `BtDatabase.create(Context)` in
 * androidMain, byte-identical to what shipped), while iOS — which has no existing
 * installs — opens a fresh v10 database (see `BtDatabase.create()` in iosMain).
 * The per-target constructor is generated by Room from [BtDatabaseConstructor];
 * it must NOT be hand-written (Room KSP rejects a hand-written actual).
 */
@Database(
    entities = [
        PortfolioEntity::class,
        HoldingEntity::class,
        TransactionEntity::class,
        PortfolioHistoryEntity::class,
        CashSourceEntity::class,
        CashMovementEntity::class,
        CashTagEntity::class,
        CustomAssetEntity::class,
        ValuePointEntity::class,
        WatchlistEntity::class,
        WatchlistItemEntity::class,
        ConglomerateEntity::class,
        ConglomeratePositionEntity::class,
        SyncOpEntity::class,
        MetaEntity::class,
        VaultEntityRow::class,
        VaultMetaRow::class,
        PriceCacheRow::class,
    ],
    version = 10,
    // Exported to shared/schemas/ (room { schemaDirectory } in shared/build.gradle.kts).
    // The golden v10 JSON (identityHash a9fab166f6bcb1451ac240972a08a408) is the
    // schema-continuity contract for the KMP/iOS port: it proves a Room build —
    // Android today, iOS tomorrow — reproduces the exact schema existing installs
    // already hold. Moving the @Database here does not change the schema, so the
    // identityHash is unchanged.
    exportSchema = true,
)
@ConstructedBy(BtDatabaseConstructor::class)
abstract class BtDatabase : RoomDatabase() {
    abstract fun portfolioDao(): PortfolioDao
    abstract fun holdingDao(): HoldingDao
    abstract fun transactionDao(): TransactionDao
    abstract fun portfolioHistoryDao(): PortfolioHistoryDao
    abstract fun cashDao(): CashDao
    abstract fun cashTagDao(): CashTagDao
    abstract fun customAssetDao(): CustomAssetDao
    abstract fun watchlistDao(): WatchlistDao
    abstract fun conglomerateDao(): ConglomerateDao
    abstract fun syncOpDao(): SyncOpDao
    abstract fun metaDao(): MetaDao
    abstract fun vaultDao(): VaultDao
    abstract fun priceCacheDao(): PriceCacheDao

    // The platform factories hang off this companion as extension functions
    // (`create(Context)` on Android, `create()` on iOS), so every existing call
    // site keeps the `BtDatabase.create(...)` form it already uses.
    companion object
}

/**
 * The per-target database constructor. Room's KSP processor generates the
 * `actual object` for each target (android / iosArm64 / iosSimulatorArm64); it
 * MUST stay an `expect` with no hand-written actual — the @ConstructedBy contract
 * requires exactly that.
 */
@Suppress("NO_ACTUAL_FOR_EXPECT", "KotlinNoActualForExpect")
internal expect object BtDatabaseConstructor : RoomDatabaseConstructor<BtDatabase> {
    override fun initialize(): BtDatabase
}
